/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebdavRouteImport } from './routes/webdav'
import { Route as TorrentRouteImport } from './routes/torrent'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as Kuaidi100RouteImport } from './routes/kuaidi100'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as IndexRouteImport } from './routes/index'

const WebdavRoute = WebdavRouteImport.update({
  id: '/webdav',
  path: '/webdav',
  getParentRoute: () => rootRouteImport,
} as any)
const TorrentRoute = TorrentRouteImport.update({
  id: '/torrent',
  path: '/torrent',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const Kuaidi100Route = Kuaidi100RouteImport.update({
  id: '/kuaidi100',
  path: '/kuaidi100',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/config': typeof ConfigRoute
  '/kuaidi100': typeof Kuaidi100Route
  '/podcast': typeof PodcastRoute
  '/torrent': typeof TorrentRoute
  '/webdav': typeof WebdavRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/config': typeof ConfigRoute
  '/kuaidi100': typeof Kuaidi100Route
  '/podcast': typeof PodcastRoute
  '/torrent': typeof TorrentRoute
  '/webdav': typeof WebdavRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/config': typeof ConfigRoute
  '/kuaidi100': typeof Kuaidi100Route
  '/podcast': typeof PodcastRoute
  '/torrent': typeof TorrentRoute
  '/webdav': typeof WebdavRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bulk'
    | '/config'
    | '/kuaidi100'
    | '/podcast'
    | '/torrent'
    | '/webdav'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bulk'
    | '/config'
    | '/kuaidi100'
    | '/podcast'
    | '/torrent'
    | '/webdav'
  id:
    | '__root__'
    | '/'
    | '/bulk'
    | '/config'
    | '/kuaidi100'
    | '/podcast'
    | '/torrent'
    | '/webdav'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulkRoute: typeof BulkRoute
  ConfigRoute: typeof ConfigRoute
  Kuaidi100Route: typeof Kuaidi100Route
  PodcastRoute: typeof PodcastRoute
  TorrentRoute: typeof TorrentRoute
  WebdavRoute: typeof WebdavRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webdav': {
      id: '/webdav'
      path: '/webdav'
      fullPath: '/webdav'
      preLoaderRoute: typeof WebdavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torrent': {
      id: '/torrent'
      path: '/torrent'
      fullPath: '/torrent'
      preLoaderRoute: typeof TorrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuaidi100': {
      id: '/kuaidi100'
      path: '/kuaidi100'
      fullPath: '/kuaidi100'
      preLoaderRoute: typeof Kuaidi100RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulkRoute: BulkRoute,
  ConfigRoute: ConfigRoute,
  Kuaidi100Route: Kuaidi100Route,
  PodcastRoute: PodcastRoute,
  TorrentRoute: TorrentRoute,
  WebdavRoute: WebdavRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
